spring.application.name=BusService
spring.datasource.url=jdbc:mysql://localhost:3306/busesdb
spring.datasource.username=root
spring.datasource.password=PHp23@pinu
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true